#! ruby
require 'test/unit'
require 'rubbish'

class TestRubbish < Test::Unit::TestCase

  def test_bash_getter
    assert_nothing_raised() do
      assert_equal 'bash', Rubbish::Bash.sh
    end
  end

  def test_bash_setter
    assert_nothing_raised() do
      sh = Rubbish::Bash.sh
      Rubbish::Bash.sh = 'bashshell'
      assert_equal 'bashshell', Rubbish::Bash.sh
      Rubbish::Bash.sh = sh
      assert_equal 'bash', Rubbish::Bash.sh
    end
  end

  def test_shells
    assert_nothing_raised() do
      assert_equal 'OK', Rubbish.bash('echo "OK"').strip
    end
  end

end
