#! ruby
require 'test/unit'
require 'rubbish'

class TestRubbish < Test::Unit::TestCase

  def test_fish_getter
    assert_nothing_raised() do
      assert_equal 'fish', Rubbish::Fish.sh
    end
  end

  def test_fish_setter
    assert_nothing_raised() do
      sh = Rubbish::Fish.sh
      Rubbish::Fish.sh = 'fishshell'
      assert_equal 'fishshell', Rubbish::Fish.sh
      Rubbish::Fish.sh = sh
      assert_equal 'fish', Rubbish::Fish.sh
    end
  end

  def test_shells
    assert_nothing_raised() do
      assert_equal 'OK', Rubbish.fish('echo "OK"').strip
    end
  end

end
