#! ruby
require 'test/unit'
require 'rubbish'

class TestRubbish < Test::Unit::TestCase
  def test_shells
    assert_equal 'OK', Rubbish.shell('bash', 'echo "OK"').strip
    assert_equal 'OK', Rubbish.shell('fish', 'echo "OK"').strip
    assert_equal 'OK', Rubbish.bash('echo "OK"').strip
    assert_equal 'OK', Rubbish.fish('echo "OK"').strip
    Rubbish::SHELL_VERSION[:ruby] = '3.0'
    assert_equal 'OK', Rubbish.ruby('puts "OK"').strip
  end
end
