#! ruby
require 'test/unit'
require 'rubbish/version'

class TestVersion < Test::Unit::TestCase
  VERSION = '0.0.0'
  def test_version
    assert_nothing_raised() do
      assert_equal VERSION, Rubbish::VERSION
      assert( system "grep version rubbish.gemspec | grep = | grep #{VERSION}" )
    end
  end
end
